# Generated by Django 3.0.7 on 2022-03-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210219_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='education',
            name='frontendlng',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='strength',
        ),
    ]
